drop table if exists appointment;
drop table if exists time_slot;
drop table if exists service_price;
drop table if exists service;
drop table if exists pet;
drop table if exists client;
drop table if exists groomer;
drop table if exists breed;
drop type if exists breed_type_enum;


CREATE TABLE client (
                        id int primary key generated by default as identity,
                        first_name VARCHAR(50) NOT NULL,
                        last_name VARCHAR(50),
                        email VARCHAR(100) NOT NULL UNIQUE,
                        phone VARCHAR(20),
                        password VARCHAR(255) NOT NULL
);


CREATE TABLE groomer (
                         id int primary key generated by default as identity,
                         first_name VARCHAR(100) NOT NULL,
                         last_name VARCHAR(100) NOT NULL,
                         career_start DATE NOT NULL,
                         email VARCHAR(100) NOT NULL UNIQUE,
                         phone VARCHAR(20)
);

CREATE TYPE breed_type_enum AS ENUM ('SMALL', 'MEDIUM', 'LARGE');

CREATE TABLE breed (
                       id SERIAL PRIMARY KEY,
                       name VARCHAR(50) NOT NULL,
                       breed_type breed_type_enum NOT NULL
);

CREATE TABLE pet (
                     id int primary key generated by default as identity,
                     name VARCHAR(50) NOT NULL,
                     species VARCHAR(10) NOT NULL check ( species = 'кошка' or species = 'собака' ),
                     breed_id int references breed (id),
                     birth_date DATE NOT NULL,
                     owner_id INT NOT NULL REFERENCES client (id) ON DELETE CASCADE
);


CREATE TABLE service (
                         id int primary key generated by default as identity,
                         name VARCHAR(50) NOT NULL,
                         description text
);

create table service_price (
                               id int primary key generated by default as identity,
                               service_id int NOT NULL REFERENCES service (id) ON DELETE CASCADE,
                               species VARCHAR(10) NOT NULL,
                               breed_type breed_type_enum,
                               price int not null check ( price > 0 )
);

create table time_slot (
                           id int primary key generated by default as identity ,
                           groomer_id INT NOT NULL REFERENCES groomer (id) ON DELETE CASCADE,
                           start_time TIMESTAMP not null,
                           end_time TIMESTAMP not null,
                           taken bool default false
);

CREATE TABLE appointment (
                             id int primary key generated by default as identity,
                             pet_id INT NOT NULL REFERENCES pet (id) ON DELETE CASCADE,
                             groomer_id INT NOT NULL REFERENCES groomer (id) ON DELETE CASCADE,
                             service_id int not null REFERENCES service (id) ON DELETE CASCADE,
                             price int not null check ( price > 0),
                             date TIMESTAMP NOT NULL,
                             notes text
);
